WITH ch(subject_name, chapter_name, ord) AS (VALUES
('Physics','Units and Measurements',1),
('Physics','Kinematics',2),
('Physics','Laws of Motion',3),
('Physics','Work, Energy and Power',4),
('Physics','Rotational Motion',5),
('Physics','Gravitation',6),
('Physics','Properties of Solids and Liquids',7),
('Physics','Thermodynamics',8),
('Physics','Kinetic Theory of Gases',9),
('Physics','Oscillations',10),
('Physics','Waves',11),
('Physics','Electrostatics',12),
('Physics','Current Electricity',13),
('Physics','Moving Charges and Magnetism',14),
('Physics','Magnetism and Matter',15),
('Physics','Electromagnetic Induction and Alternating Current',16),
('Physics','Electromagnetic Waves',17),
('Physics','Optics',18),
('Physics','Dual Nature of Matter and Radiation',19),
('Physics','Atoms and Nuclei',20),
('Physics','Semiconductor Electronics',21),
('Chemistry','Some Basic Concepts of Chemistry',1),
('Chemistry','Atomic Structure',2),
('Chemistry','Chemical Bonding and Molecular Structure',3),
('Chemistry','States of Matter',4),
('Chemistry','Chemical Thermodynamics',5),
('Chemistry','Equilibrium',6),
('Chemistry','Redox Reactions',7),
('Chemistry','Electrochemistry',8),
('Chemistry','Chemical Kinetics',9),
('Chemistry','Solutions',10),
('Chemistry','Classification of Elements and Periodicity',11),
('Chemistry','p-Block Elements',12),
('Chemistry','d- and f-Block Elements',13),
('Chemistry','Coordination Compounds',14),
('Chemistry','Purification and Characterisation of Organic Compounds',15),
('Chemistry','Basic Principles of Organic Chemistry',16),
('Chemistry','Hydrocarbons',17),
('Chemistry','Haloalkanes and Haloarenes',18),
('Chemistry','Alcohols, Phenols and Ethers',19),
('Chemistry','Aldehydes, Ketones and Carboxylic Acids',20),
('Chemistry','Organic Compounds Containing Nitrogen',21),
('Chemistry','Biomolecules',22),
('Chemistry','Principles of Practical Chemistry',23),
('Mathematics','Sets, Relations and Functions',1),
('Mathematics','Complex Numbers and Quadratic Equations',2),
('Mathematics','Matrices and Determinants',3),
('Mathematics','Permutations and Combinations',4),
('Mathematics','Binomial Theorem',5),
('Mathematics','Sequences and Series',6),
('Mathematics','Limits, Continuity and Differentiability',7),
('Mathematics','Applications of Derivatives',8),
('Mathematics','Integral Calculus',9),
('Mathematics','Differential Equations',10),
('Mathematics','Coordinate Geometry',11),
('Mathematics','Three Dimensional Geometry',12),
('Mathematics','Vector Algebra',13),
('Mathematics','Statistics',14),
('Mathematics','Probability',15),
('Mathematics','Trigonometry',16),
('Mathematics','Mathematical Reasoning',17),
('Botany','The Living World',1),
('Botany','Biological Classification',2),
('Botany','Plant Kingdom',3),
('Botany','Morphology of Flowering Plants',4),
('Botany','Anatomy of Flowering Plants',5),
('Botany','Cell: The Unit of Life',6),
('Botany','Cell Cycle and Cell Division',7),
('Botany','Photosynthesis in Higher Plants',8),
('Botany','Respiration in Plants',9),
('Botany','Plant Growth and Development',10),
('Botany','Sexual Reproduction in Flowering Plants',11),
('Botany','Principles of Inheritance and Variation',12),
('Botany','Molecular Basis of Inheritance',13),
('Botany','Microbes in Human Welfare',14),
('Botany','Biotechnology: Principles and Processes',15),
('Botany','Biotechnology and its Applications',16),
('Botany','Organisms and Populations',17),
('Botany','Ecosystem',18),
('Botany','Biodiversity and Conservation',19),
('Zoology','Animal Kingdom',1),
('Zoology','Structural Organisation in Animals',2),
('Zoology','Biomolecules of the Cell',3),
('Zoology','Breathing and Exchange of Gases',4),
('Zoology','Body Fluids and Circulation',5),
('Zoology','Excretory Products and their Elimination',6),
('Zoology','Locomotion and Movement',7),
('Zoology','Neural Control and Coordination',8),
('Zoology','Chemical Coordination and Integration',9),
('Zoology','Human Reproduction',10),
('Zoology','Reproductive Health',11),
('Zoology','Evolution',12),
('Zoology','Human Health and Disease',13),
('Zoology','Animal Husbandry',14),
('English Proficiency','Grammar',1),
('English Proficiency','Vocabulary',2),
('English Proficiency','Reading Comprehension',3),
('English Proficiency','Composition',4),
('Logical Reasoning','Verbal Reasoning',1),
('Logical Reasoning','Nonverbal Reasoning',2),
('Logical Reasoning','Analytical Reasoning',3)
)
INSERT INTO public.chapters (subject_id, name, sort_order)
SELECT s.id, ch.chapter_name, ch.ord
FROM ch JOIN public.subjects s ON s.name = ch.subject_name
WHERE NOT EXISTS (SELECT 1 FROM public.chapters c WHERE c.subject_id = s.id AND c.name = ch.chapter_name);

WITH tp(subject_name, chapter_name, topic_name, ord) AS (VALUES
('Physics','Units and Measurements','Physical quantities and SI units',1),
('Physics','Units and Measurements','Dimensional analysis',2),
('Physics','Units and Measurements','Errors in measurement',3),
('Physics','Kinematics','Motion in a straight line',1),
('Physics','Kinematics','Relative velocity',2),
('Physics','Kinematics','Projectile motion',3),
('Physics','Kinematics','Vectors in kinematics',4),
('Physics','Laws of Motion','Newton''s laws',1),
('Physics','Laws of Motion','Friction',2),
('Physics','Laws of Motion','Circular motion dynamics',3),
('Physics','Work, Energy and Power','Work-energy theorem',1),
('Physics','Work, Energy and Power','Conservation of energy',2),
('Physics','Work, Energy and Power','Collisions',3),
('Physics','Rotational Motion','Centre of mass',1),
('Physics','Rotational Motion','Moment of inertia',2),
('Physics','Rotational Motion','Torque and angular momentum',3),
('Physics','Rotational Motion','Rolling motion',4),
('Physics','Gravitation','Newton''s law of gravitation',1),
('Physics','Gravitation','Gravitational potential energy',2),
('Physics','Gravitation','Satellites and orbits',3),
('Physics','Properties of Solids and Liquids','Elasticity',1),
('Physics','Properties of Solids and Liquids','Fluid pressure and Bernoulli''s principle',2),
('Physics','Properties of Solids and Liquids','Viscosity and surface tension',3),
('Physics','Thermodynamics','Zeroth and first law',1),
('Physics','Thermodynamics','Second law and heat engines',2),
('Physics','Thermodynamics','Thermal properties of matter',3),
('Physics','Kinetic Theory of Gases','Ideal gas equation',1),
('Physics','Kinetic Theory of Gases','Degrees of freedom',2),
('Physics','Kinetic Theory of Gases','Mean free path',3),
('Physics','Oscillations','Simple harmonic motion',1),
('Physics','Oscillations','Spring and pendulum systems',2),
('Physics','Oscillations','Damped and forced oscillations',3),
('Physics','Waves','Wave motion and equations',1),
('Physics','Waves','Superposition and standing waves',2),
('Physics','Waves','Doppler effect',3),
('Physics','Electrostatics','Coulomb''s law and electric field',1),
('Physics','Electrostatics','Gauss''s law',2),
('Physics','Electrostatics','Electric potential',3),
('Physics','Electrostatics','Capacitors',4),
('Physics','Current Electricity','Ohm''s law and resistivity',1),
('Physics','Current Electricity','Kirchhoff''s laws',2),
('Physics','Current Electricity','Wheatstone bridge and potentiometer',3),
('Physics','Moving Charges and Magnetism','Biot-Savart law',1),
('Physics','Moving Charges and Magnetism','Ampere''s circuital law',2),
('Physics','Moving Charges and Magnetism','Force on current carrying conductors',3),
('Physics','Magnetism and Matter','Bar magnet and magnetic dipole',1),
('Physics','Magnetism and Matter','Earth''s magnetism',2),
('Physics','Magnetism and Matter','Magnetic materials',3),
('Physics','Electromagnetic Induction and Alternating Current','Faraday''s law and Lenz''s law',1),
('Physics','Electromagnetic Induction and Alternating Current','Self and mutual inductance',2),
('Physics','Electromagnetic Induction and Alternating Current','AC circuits and resonance',3),
('Physics','Electromagnetic Waves','Displacement current',1),
('Physics','Electromagnetic Waves','Electromagnetic spectrum',2),
('Physics','Optics','Reflection and refraction',1),
('Physics','Optics','Lenses and optical instruments',2),
('Physics','Optics','Interference and diffraction',3),
('Physics','Optics','Polarisation',4),
('Physics','Dual Nature of Matter and Radiation','Photoelectric effect',1),
('Physics','Dual Nature of Matter and Radiation','de Broglie wavelength',2),
('Physics','Atoms and Nuclei','Bohr model and spectra',1),
('Physics','Atoms and Nuclei','Radioactivity',2),
('Physics','Atoms and Nuclei','Nuclear fission and fusion',3),
('Physics','Semiconductor Electronics','Semiconductors and diodes',1),
('Physics','Semiconductor Electronics','Transistors',2),
('Physics','Semiconductor Electronics','Logic gates',3),
('Chemistry','Some Basic Concepts of Chemistry','Mole concept',1),
('Chemistry','Some Basic Concepts of Chemistry','Stoichiometry',2),
('Chemistry','Some Basic Concepts of Chemistry','Empirical and molecular formula',3),
('Chemistry','Atomic Structure','Bohr model and spectra',1),
('Chemistry','Atomic Structure','Quantum numbers',2),
('Chemistry','Atomic Structure','Electronic configuration',3),
('Chemistry','Chemical Bonding and Molecular Structure','Ionic and covalent bonding',1),
('Chemistry','Chemical Bonding and Molecular Structure','VSEPR and hybridisation',2),
('Chemistry','Chemical Bonding and Molecular Structure','Molecular orbital theory',3),
('Chemistry','States of Matter','Gas laws',1),
('Chemistry','States of Matter','Kinetic molecular theory',2),
('Chemistry','States of Matter','Liquid state',3),
('Chemistry','Chemical Thermodynamics','Enthalpy and Hess''s law',1),
('Chemistry','Chemical Thermodynamics','Entropy and Gibbs energy',2),
('Chemistry','Chemical Thermodynamics','Spontaneity',3),
('Chemistry','Equilibrium','Chemical equilibrium and Kc/Kp',1),
('Chemistry','Equilibrium','Ionic equilibrium and pH',2),
('Chemistry','Equilibrium','Buffers and solubility product',3),
('Chemistry','Redox Reactions','Oxidation number',1),
('Chemistry','Redox Reactions','Balancing redox reactions',2),
('Chemistry','Electrochemistry','Electrode potential and cells',1),
('Chemistry','Electrochemistry','Nernst equation',2),
('Chemistry','Electrochemistry','Conductance and electrolysis',3),
('Chemistry','Chemical Kinetics','Rate laws and order',1),
('Chemistry','Chemical Kinetics','Integrated rate equations',2),
('Chemistry','Chemical Kinetics','Arrhenius equation',3),
('Chemistry','Solutions','Concentration terms',1),
('Chemistry','Solutions','Raoult''s law',2),
('Chemistry','Solutions','Colligative properties',3),
('Chemistry','Classification of Elements and Periodicity','Periodic table trends',1),
('Chemistry','Classification of Elements and Periodicity','Periodic properties',2),
('Chemistry','p-Block Elements','Group 13 and 14',1),
('Chemistry','p-Block Elements','Group 15 and 16',2),
('Chemistry','p-Block Elements','Group 17 and 18',3),
('Chemistry','d- and f-Block Elements','Transition elements',1),
('Chemistry','d- and f-Block Elements','Lanthanoids and actinoids',2),
('Chemistry','Coordination Compounds','Nomenclature and isomerism',1),
('Chemistry','Coordination Compounds','Werner and crystal field theory',2),
('Chemistry','Purification and Characterisation of Organic Compounds','Purification methods',1),
('Chemistry','Purification and Characterisation of Organic Compounds','Qualitative and quantitative analysis',2),
('Chemistry','Basic Principles of Organic Chemistry','IUPAC nomenclature',1),
('Chemistry','Basic Principles of Organic Chemistry','Isomerism',2),
('Chemistry','Basic Principles of Organic Chemistry','Electronic effects and reaction mechanisms',3),
('Chemistry','Hydrocarbons','Alkanes',1),
('Chemistry','Hydrocarbons','Alkenes and alkynes',2),
('Chemistry','Hydrocarbons','Aromatic hydrocarbons',3),
('Chemistry','Haloalkanes and Haloarenes','Nucleophilic substitution',1),
('Chemistry','Haloalkanes and Haloarenes','Preparation and properties',2),
('Chemistry','Alcohols, Phenols and Ethers','Alcohols',1),
('Chemistry','Alcohols, Phenols and Ethers','Phenols',2),
('Chemistry','Alcohols, Phenols and Ethers','Ethers',3),
('Chemistry','Aldehydes, Ketones and Carboxylic Acids','Carbonyl preparation and properties',1),
('Chemistry','Aldehydes, Ketones and Carboxylic Acids','Nucleophilic addition',2),
('Chemistry','Aldehydes, Ketones and Carboxylic Acids','Carboxylic acids and derivatives',3),
('Chemistry','Organic Compounds Containing Nitrogen','Amines',1),
('Chemistry','Organic Compounds Containing Nitrogen','Diazonium salts',2),
('Chemistry','Biomolecules','Carbohydrates',1),
('Chemistry','Biomolecules','Proteins and enzymes',2),
('Chemistry','Biomolecules','Nucleic acids and vitamins',3),
('Chemistry','Principles of Practical Chemistry','Salt analysis',1),
('Chemistry','Principles of Practical Chemistry','Organic functional group tests',2),
('Mathematics','Sets, Relations and Functions','Sets and operations',1),
('Mathematics','Sets, Relations and Functions','Relations',2),
('Mathematics','Sets, Relations and Functions','Types of functions',3),
('Mathematics','Complex Numbers and Quadratic Equations','Algebra of complex numbers',1),
('Mathematics','Complex Numbers and Quadratic Equations','Argand plane and polar form',2),
('Mathematics','Complex Numbers and Quadratic Equations','Quadratic equations and roots',3),
('Mathematics','Matrices and Determinants','Matrix algebra',1),
('Mathematics','Matrices and Determinants','Determinants and properties',2),
('Mathematics','Matrices and Determinants','Inverse and system of equations',3),
('Mathematics','Permutations and Combinations','Fundamental principle of counting',1),
('Mathematics','Permutations and Combinations','Permutations',2),
('Mathematics','Permutations and Combinations','Combinations',3),
('Mathematics','Binomial Theorem','General and middle terms',1),
('Mathematics','Binomial Theorem','Binomial applications',2),
('Mathematics','Sequences and Series','Arithmetic progression',1),
('Mathematics','Sequences and Series','Geometric progression',2),
('Mathematics','Sequences and Series','Special series',3),
('Mathematics','Limits, Continuity and Differentiability','Limits',1),
('Mathematics','Limits, Continuity and Differentiability','Continuity',2),
('Mathematics','Limits, Continuity and Differentiability','Differentiability and derivatives',3),
('Mathematics','Applications of Derivatives','Rate of change and tangents',1),
('Mathematics','Applications of Derivatives','Maxima and minima',2),
('Mathematics','Applications of Derivatives','Monotonicity',3),
('Mathematics','Integral Calculus','Indefinite integrals',1),
('Mathematics','Integral Calculus','Definite integrals',2),
('Mathematics','Integral Calculus','Area under curves',3),
('Mathematics','Differential Equations','Order and degree',1),
('Mathematics','Differential Equations','Variable separable equations',2),
('Mathematics','Differential Equations','Linear differential equations',3),
('Mathematics','Coordinate Geometry','Straight lines',1),
('Mathematics','Coordinate Geometry','Circles',2),
('Mathematics','Coordinate Geometry','Parabola, ellipse and hyperbola',3),
('Mathematics','Three Dimensional Geometry','Direction cosines',1),
('Mathematics','Three Dimensional Geometry','Lines in space',2),
('Mathematics','Three Dimensional Geometry','Planes',3),
('Mathematics','Vector Algebra','Vector operations',1),
('Mathematics','Vector Algebra','Scalar and vector products',2),
('Mathematics','Statistics','Measures of central tendency',1),
('Mathematics','Statistics','Measures of dispersion',2),
('Mathematics','Probability','Conditional probability',1),
('Mathematics','Probability','Bayes theorem',2),
('Mathematics','Probability','Random variables and distributions',3),
('Mathematics','Trigonometry','Trigonometric ratios and identities',1),
('Mathematics','Trigonometry','Trigonometric equations',2),
('Mathematics','Trigonometry','Inverse trigonometric functions',3),
('Mathematics','Trigonometry','Heights and distances',4),
('Mathematics','Mathematical Reasoning','Statements and logical connectives',1),
('Botany','The Living World','Taxonomic categories',1),
('Botany','The Living World','Taxonomical aids',2),
('Botany','Biological Classification','Five kingdom classification',1),
('Botany','Biological Classification','Viruses, viroids and lichens',2),
('Botany','Plant Kingdom','Algae and bryophytes',1),
('Botany','Plant Kingdom','Pteridophytes',2),
('Botany','Plant Kingdom','Gymnosperms and angiosperms',3),
('Botany','Morphology of Flowering Plants','Root, stem and leaf',1),
('Botany','Morphology of Flowering Plants','Inflorescence and flower',2),
('Botany','Morphology of Flowering Plants','Fruit and seed',3),
('Botany','Anatomy of Flowering Plants','Plant tissues',1),
('Botany','Anatomy of Flowering Plants','Tissue systems',2),
('Botany','Anatomy of Flowering Plants','Secondary growth',3),
('Botany','Cell: The Unit of Life','Cell theory and structure',1),
('Botany','Cell: The Unit of Life','Cell organelles',2),
('Botany','Cell: The Unit of Life','Cell membrane and cell wall',3),
('Botany','Cell Cycle and Cell Division','Mitosis',1),
('Botany','Cell Cycle and Cell Division','Meiosis',2),
('Botany','Photosynthesis in Higher Plants','Light reaction',1),
('Botany','Photosynthesis in Higher Plants','C3 and C4 pathways',2),
('Botany','Photosynthesis in Higher Plants','Factors affecting photosynthesis',3),
('Botany','Respiration in Plants','Glycolysis',1),
('Botany','Respiration in Plants','Krebs cycle',2),
('Botany','Respiration in Plants','Electron transport system',3),
('Botany','Plant Growth and Development','Growth phases',1),
('Botany','Plant Growth and Development','Plant growth regulators',2),
('Botany','Plant Growth and Development','Photoperiodism and vernalisation',3),
('Botany','Sexual Reproduction in Flowering Plants','Pre-fertilisation events',1),
('Botany','Sexual Reproduction in Flowering Plants','Double fertilisation',2),
('Botany','Sexual Reproduction in Flowering Plants','Post-fertilisation events',3),
('Botany','Principles of Inheritance and Variation','Mendelian inheritance',1),
('Botany','Principles of Inheritance and Variation','Chromosomal theory of inheritance',2),
('Botany','Principles of Inheritance and Variation','Genetic disorders',3),
('Botany','Molecular Basis of Inheritance','DNA structure and replication',1),
('Botany','Molecular Basis of Inheritance','Transcription and translation',2),
('Botany','Molecular Basis of Inheritance','Gene regulation',3),
('Botany','Microbes in Human Welfare','Microbes in industry',1),
('Botany','Microbes in Human Welfare','Microbes in sewage treatment',2),
('Botany','Biotechnology: Principles and Processes','Recombinant DNA technology',1),
('Botany','Biotechnology: Principles and Processes','Tools and bioreactors',2),
('Botany','Biotechnology and its Applications','Applications in agriculture',1),
('Botany','Biotechnology and its Applications','Applications in medicine',2),
('Botany','Organisms and Populations','Population attributes',1),
('Botany','Organisms and Populations','Population interactions',2),
('Botany','Ecosystem','Energy flow',1),
('Botany','Ecosystem','Nutrient cycling',2),
('Botany','Ecosystem','Ecological pyramids',3),
('Botany','Biodiversity and Conservation','Patterns of biodiversity',1),
('Botany','Biodiversity and Conservation','Conservation strategies',2),
('Zoology','Animal Kingdom','Basis of classification',1),
('Zoology','Animal Kingdom','Non-chordates',2),
('Zoology','Animal Kingdom','Chordates',3),
('Zoology','Structural Organisation in Animals','Animal tissues',1),
('Zoology','Structural Organisation in Animals','Frog morphology and anatomy',2),
('Zoology','Biomolecules of the Cell','Proteins and enzymes',1),
('Zoology','Biomolecules of the Cell','Carbohydrates and lipids',2),
('Zoology','Biomolecules of the Cell','Nucleic acids',3),
('Zoology','Breathing and Exchange of Gases','Respiratory organs',1),
('Zoology','Breathing and Exchange of Gases','Transport of gases',2),
('Zoology','Breathing and Exchange of Gases','Respiratory disorders',3),
('Zoology','Body Fluids and Circulation','Blood and lymph',1),
('Zoology','Body Fluids and Circulation','Human circulatory system',2),
('Zoology','Body Fluids and Circulation','Cardiac cycle and disorders',3),
('Zoology','Excretory Products and their Elimination','Human excretory system',1),
('Zoology','Excretory Products and their Elimination','Urine formation and regulation',2),
('Zoology','Locomotion and Movement','Muscle contraction',1),
('Zoology','Locomotion and Movement','Skeletal system and joints',2),
('Zoology','Neural Control and Coordination','Neuron and nerve impulse',1),
('Zoology','Neural Control and Coordination','Central nervous system',2),
('Zoology','Neural Control and Coordination','Sense organs',3),
('Zoology','Chemical Coordination and Integration','Endocrine glands',1),
('Zoology','Chemical Coordination and Integration','Hormones and mechanism of action',2),
('Zoology','Human Reproduction','Male and female reproductive systems',1),
('Zoology','Human Reproduction','Gametogenesis and menstrual cycle',2),
('Zoology','Human Reproduction','Fertilisation and embryonic development',3),
('Zoology','Reproductive Health','Contraception',1),
('Zoology','Reproductive Health','Assisted reproductive technologies',2),
('Zoology','Evolution','Origin of life',1),
('Zoology','Evolution','Evidences of evolution',2),
('Zoology','Evolution','Mechanism and human evolution',3),
('Zoology','Human Health and Disease','Infectious diseases',1),
('Zoology','Human Health and Disease','Immunity',2),
('Zoology','Human Health and Disease','Drugs and alcohol abuse',3),
('Zoology','Animal Husbandry','Animal breeding',1),
('Zoology','Animal Husbandry','Apiculture and fisheries',2),
('English Proficiency','Grammar','Tenses and agreement',1),
('English Proficiency','Grammar','Articles and prepositions',2),
('English Proficiency','Grammar','Voice and narration',3),
('English Proficiency','Vocabulary','Synonyms and antonyms',1),
('English Proficiency','Vocabulary','One word substitution',2),
('English Proficiency','Vocabulary','Idioms and phrases',3),
('English Proficiency','Reading Comprehension','Content based comprehension',1),
('English Proficiency','Reading Comprehension','Inference and tone',2),
('English Proficiency','Composition','Rearrangement of sentences',1),
('English Proficiency','Composition','Sentence improvement',2),
('Logical Reasoning','Verbal Reasoning','Analogy',1),
('Logical Reasoning','Verbal Reasoning','Classification',2),
('Logical Reasoning','Verbal Reasoning','Series completion',3),
('Logical Reasoning','Verbal Reasoning','Logical deduction',4),
('Logical Reasoning','Nonverbal Reasoning','Pattern perception',1),
('Logical Reasoning','Nonverbal Reasoning','Figure formation and analysis',2),
('Logical Reasoning','Nonverbal Reasoning','Paper cutting and folding',3),
('Logical Reasoning','Nonverbal Reasoning','Figure matrix',4),
('Logical Reasoning','Analytical Reasoning','Seating arrangement',1),
('Logical Reasoning','Analytical Reasoning','Blood relations',2),
('Logical Reasoning','Analytical Reasoning','Direction sense',3)
)
INSERT INTO public.topics (chapter_id, name, sort_order)
SELECT c.id, tp.topic_name, tp.ord
FROM tp
JOIN public.subjects s ON s.name = tp.subject_name
JOIN public.chapters c ON c.subject_id = s.id AND c.name = tp.chapter_name
WHERE NOT EXISTS (SELECT 1 FROM public.topics t WHERE t.chapter_id = c.id AND t.name = tp.topic_name);
